### ISSUE TITLE
Question on using multiBaC

### ISSUE THREAD

**Issue by PelFritz** [ConesaLab/MultiBaC#1]
Hi, I have an RNA seq data produced by alignment with kaillsto. When using the normal limma workflow I realised there was a huge batch effect within the data. I stumbled on the MultiBac tool online and was wondering if it was correct to use it to remove batch effect before Differential gene expression analysis.

**Comment by ManuelUgidos** [comment]
Hi, first of all I apologize for the delay and appreciate for your interest in our tool. Indeed, MultiBaC was conceived for batch effect removal in different scenarios and should be applied before performing any statistical analysis. I would need more information about your experimental setting since MultiBaC has three modes: single omic level correction when the source of the batch effect is known, when the source is unknown and multiomic level correction. I encourage you to visit the package at Bioconductor, in particular the user’s guide where you can find which mode will solve your batch effect problem (http://www.bioconductor.org/packages/release/bioc/vignettes/MultiBaC/inst/doc/MultiBaC.html). I hope I’ve helped you.
